### ISSUE TITLE
Failed to parse error response

### ISSUE THREAD

**Issue by QiXi** [greymag/tinkoff-invest-openapi-dart-sdk#5]
Заведу такой баг, так как повторился второй раз. 
Для обработки истории операций был написан следующий метод:
```
Future<void> loadOperations() async {
    final to = DateTime.now();
    final from = DateTime.fromMillisecondsSinceEpoch(to.millisecondsSinceEpoch - 86400000);
    final response =
        await api.operations.load(from, to, brokerAccountId: properties.brokerAccountId);
    if (response.isValue) {
      final list = response.asValue!.value.payload;
      for (var operation in list.operations) {
        state.updateOperation(operation);
      }
    } else {
      error('Load operations failed: ${response.asError!.error}');
    }
  }
```
Лог выводит сообщение:
> [E]  Load operations failed: Failed to parse error response

Предположу что парсер умер при получении незнакомых данных.

**Comment by greymag** [comment]
Да, явно какой-то косяк. А есть распечатка ответа? Чтобы понять какие данные он не смог распарсить

**Comment by QiXi** [comment]
> Да, явно какой-то косяк. А есть распечатка ответа? Чтобы понять какие данные он не смог распарсить

Полученный ответ оставлю когда поймаю еще раз, но уже в дебаге.

**Comment by QiXi** [comment]
Работало два экземпляра программы в дебаге и в один и тотже момент поймали такие логи
```*** DioError ***:
uri: https://api-invest.tinkoff.ru/openapi/operations?from=2021-08-23T11%3A56%3A52.580Z&to=2021-08-24T11%3A56%3A52.580678Z
DioError [DioErrorType.connectTimeout]: Connecting timed out [3000ms]
#0      DioMixin.assureDioError (package:dio/src/dio_mixin.dart:819)
#1      DioMixin._dispatchRequest (package:dio/src/dio_mixin.dart:678)
<asynchronous suspension>
#2      DioMixin.fetch.<anonymous closure>.<anonymous closure> (package:dio/src/dio_mixin.dart:586)
<asynchronous suspension>

[E]  Load operations failed: Failed to parse error response
```

```
*** DioError ***:
uri: https://api-invest.tinkoff.ru/openapi/operations?from=2021-08-23T11%3A57%3A56.519Z&to=2021-08-24T11%3A57%3A56.519742Z
DioError [DioErrorType.response]: Http status error [500]
#0      DioMixin.assureDioError (package:dio/src/dio_mixin.dart:819)
#1      DioMixin._dispatchRequest (package:dio/src/dio_mixin.dart:678)
<asynchronous suspension>
#2      DioMixin.fetch.<anonymous closure>.<anonymous closure> (package:dio/src/dio_mixin.dart:586)
<asynchronous suspension>

uri: https://api-invest.tinkoff.ru/openapi/operations?from=2021-08-23T11%3A57%3A56.519Z&to=2021-08-24T11%3A57%3A56.519742Z
statusCode: 500
headers:
 transfer-encoding: chunked
 date: Tue, 24 Aug 2021 11:57:56 GMT
 server: nginx
 x-edge-processing-time: 2
Response Text:

[E]  Load operations failed: Failed to parse error response
```
